dofile("tests/lua/privacy_spec.lua")
dofile("tests/lua/collector_spec.lua")
dofile("tests/lua/aggregation_spec.lua")
dofile("tests/lua/mapping_attribution_spec.lua")
dofile("tests/lua/key_tokens_spec.lua")
dofile("tests/lua/keymap_snapshot_spec.lua")
dofile("tests/lua/snapshot_payload_spec.lua")
dofile("tests/lua/mapping_resolver_spec.lua")
dofile("tests/lua/collector_attribution_spec.lua")
dofile("tests/lua/callback_performance_spec.lua")
dofile("tests/lua/init_report_spec.lua")
dofile("tests/lua/retention_spec.lua")
dofile("tests/lua/filesystem_spec.lua")
dofile("tests/lua/report_spec.lua")
dofile("tests/lua/purge_spec.lua")

print("Lua test suite: ok")
